spring:
  application:
    name: TestOauthServer
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=OauthServer
    username: sa
    password: qwertyuiop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
#security:
#    user:
#      password: password
#    oauth2:
#      resource:
#        filter-order: 3


## Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
## spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

## Hibernate ddl auto (create, create-drop, validate, update)
  